### PR TITLE
Maven

### PR DESCRIPTION
**Pull request by Endolf**
Fix for #22

### CODE REVIEW

**Comment by neilyoung** [comment]
@Endolf What is the most recent version at Maven now?

**Comment by Endolf** [comment]
2.0.7 is in maven central, there are other items planned for the [2.0.8 milestone](https://github.com/jinput/jinput/milestone/1), once they are completed another release to maven central will happen.

**Comment by Endolf** [comment]
2.0.8-SNAPSHOT is now in maven central if you wish to use the maven central snapshot repo. I've also updated the examples [pom](https://github.com/jinput/jinput/blob/master/examples/pom.xml) to show using the new dependencies and using the native dependencies plugin to get the natives exported.

**Comment by neilyoung** [comment]
Hmm. Can't get the natives deployed...

Using IntellijIdea, added coreapi-snapshot and osx-plugin as maven dependencies

.iml: 
```

    <orderEntry type="library" name="net.java.jinput:coreapi:2.0.8-SNAPSHOT" level="project" />
    <orderEntry type="library" name="net.java.jinput:osx-plugin:2.0.8-SNAPSHOT" level="project" />

```
Getting 

`java.lang.UnsatisfiedLinkError: no jinput-osx in java.library.path
`

at runtime.

**Comment by Endolf** [comment]
I don't use osx (except to build JInput) and I don't hand craft intellij project files, but I can offer the following. That unsatisfied link error means you don't have the osx natives on you java.library.path.

If you're using maven then the osx-plugin jar with a classifier of natives-os contains them and the natives dependency plugin will unpack it automatically (see the examples pom I linked).

If you are not using maven, then you'll have to pull the jnilib out of that jar file manually and set the java.library.path property on your java command that executes your project.

**Comment by neilyoung** [comment]
@Endolf Yes, makes sense.  But I cannot see something like a `libjinput-osx.jnilib` in the jar...

**Comment by neilyoung** [comment]
If the maven approach does not work for IntelliJ would you mind to provide a downloadable JAR plus natives as like now? https://github.com/jinput/jinput/wiki/Getting-started-with-JInput

**Comment by Endolf** [comment]
`jar -tf ~/.m2/repository/net/java/jinput/osx-plugin/2.0.8-SNAPSHOT/osx-plugin-2.0.8-SNAPSHOT-natives-osx.jar` revels the following for me
`META-INF/MANIFEST.MF
META-INF/
META-INF/maven/
META-INF/maven/net.java.jinput/
META-INF/maven/net.java.jinput/osx-plugin/
libjinput-osx.jnilib
META-INF/maven/net.java.jinput/osx-plugin/pom.xml
META-INF/maven/net.java.jinput/osx-plugin/pom.properties`

Not sure how yours doesn't contain the jnilib, is it worth an mvn -U to update snapshots?

**Comment by neilyoung** [comment]
Hmm. No. I didn't add the natives-osx.jar, because I didn't find it. I was looking for `jinput` and there were the a.m. packages, which seemed to be close. So the `net.java.jinput:osx-plugin:2.0.8-SNAPSHOT` does definitely not contain the natives. The Intellij project dependency dialog cannot find it, obviuously.

**Comment by neilyoung** [comment]
This is what I see there.

image

**Comment by Endolf** [comment]
Sorry, I don't use the IDE to download jars either, I include them in my pom, see the pom file I linked above. I don't know how to add a classifier in the tool you are using, which is what you need to do. If you're not using the natives plugin (again, as shown in the examples pom) you'll need to unpack that jar once you've downloaded it.

**Comment by neilyoung** [comment]
What is the full classifier of the native package?

**Comment by neilyoung** [comment]
This is the content of

~/.m2/repository/net/java/jinput/osx-plugin/2.0.8-SNAPSHOT $ tree
.
├── _remote.repositories
├── maven-metadata-central-snapshots.xml
├── maven-metadata-central-snapshots.xml.sha1
├── maven-metadata-jboss.community.xml
├── maven-metadata-jboss.community.xml.sha1
├── osx-plugin-2.0.8-20180524.190702-3.jar
├── osx-plugin-2.0.8-20180524.190702-3.jar.sha1
├── osx-plugin-2.0.8-20180524.190702-3.pom
├── osx-plugin-2.0.8-20180524.190702-3.pom.sha1
├── osx-plugin-2.0.8-20180524.202234-4.jar
├── osx-plugin-2.0.8-20180524.202234-4.jar.sha1
├── osx-plugin-2.0.8-20180524.202234-4.pom
├── osx-plugin-2.0.8-20180524.202234-4.pom.sha1
├── osx-plugin-2.0.8-SNAPSHOT.jar
├── osx-plugin-2.0.8-SNAPSHOT.pom
└── resolver-status.properties

0 directories, 16 files

There is no such a thing like osx-plugin-2.0.8-SNAPSHOT-natives-osx.jar

**Comment by neilyoung** [comment]
@Endolf Would you consider to give IntellijIDEA a try? I mean, it is not that exotic, as it seems. I guess, it is widely used for Java development and it is cross platform. The IDE is free (community edition) and a HelloWorld is quickly done. I can guide you through the process of using Maven packages, it is as easy as thinkable. I'm using tons of Maven projects this way (w/o using maven or gradle as build system) and I don't really know, why I'm unable to include your native packages.

**Comment by Endolf** [comment]
You won't see that file in the directory until you've downloaded it. If you look at maven central for the osx plugin it's there (2.0.8 was released last night) http://repo1.maven.org/maven2/net/java/jinput/osx-plugin/2.0.8/

I do use intellij myself, but I use pom files rather than their own library tool for managing my dependencies as that works across teams where other people are using different IDEs

**Comment by neilyoung** [comment]
Thanks for your patience. This is, what I get: No natives...

image

**Comment by neilyoung** [comment]
Since I'm just interested in switching the logging, off, I have have copied the 2.0.7 natives to my lib dir. It seems to work so far. Could you confirm, that this could work generally? Or is there a compatibility issue with 2.0.8/2.0.9?

**Comment by Endolf** [comment]
If you just want to download the natives jar file then download osx-plugin-2.0.8-natives-osx.jar from the maven central link I shared a couple of comments back. One of the features marked for 2.0.9 is an uber jar, which will be 1 jar for all of the java jinput runtime code, and 1 jar for all the natives code. I'll be able to add links to the github site pages that are also part of 2.0.9

**Comment by neilyoung** [comment]
Did that already. Thanks. Works

**Comment by neilyoung** [comment]
@Endolf One additional question: Just noticed, that there is no 32 bit Linux binary anymore. By design?

**Comment by Endolf** [comment]
It is, yes. There is nothing to stop it being built for 32 bit systems, but Ubuntu for example no longer support 32 bit (18.04, the current LTS doesn't ship for 32 bit) and the JDKs are no longer shipping 32 bit versions, 32 bit versions of JInput prebuilt have been dropped too.

**Comment by neilyoung** [comment]
@Endolf No problem with this. Thanks for the information

**Pull request merged**
